version: '3.1'
services:
  keycloak: 
    image: nxhanh/numberio-keycloak:latest
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    command: start-dev
